// This is the content of the pinDefs.h file that declares what function is
// given to each pin.

// Motors

// Front Left
#define FRONT_LEFT_MOTOR_SPEED_PIN D2
#define FRONT_LEFT_MOTOR_ENCODER_PRI_PIN D6
#define FRONT_LEFT_MOTOR_ENCODER_SEC_PIN D7

// Front Right
#define FRONT_RIGHT_MOTOR_SPEED_PIN D3
#define FRONT_RIGHT_MOTOR_ENCODER_PRI_PIN D8
#define FRONT_RIGHT_MOTOR_ENCODER_SEC_PIN D9

// Back Left
#define BACK_LEFT_MOTOR_SPEED_PIN D4
#define BACK_LEFT_MOTOR_ENCODER_PRI_PIN D10
#define BACK_LEFT_MOTOR_ENCODER_SEC_PIN D11

// Back Right
#define BACK_RIGHT_MOTOR_SPEED_PIN D5
#define BACK_RIGHT_MOTOR_ENCODER_PRI_PIN A6
#define BACK_RIGHT_MOTOR_ENCODER_SEC_PIN A7


// Shift Reg
#define SHIFT_REG_DATA A0
#define SHIFT_REG_LATCH A1
#define SHIFT_REG_CLOCK A2
